# Generated by Django 4.2.4 on 2023-08-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_teacher_subject_mark_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='marks_obtained',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
