# Generated by Django 4.2.4 on 2023-09-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_alter_mark_marks_obtained'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dep_image',
            field=models.URLField(default='None', max_length=2083),
        ),
    ]
